apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/instance: redis
  name: auth-api
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: auth-api
    app.kubernetes.io/instance: redis
  type: ClusterIP
status:
  loadBalancer: {}
