apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app.kubernetes.io/name: redis-commander
    app.kubernetes.io/instance: redis
spec:
  type: ClusterIP
  selector:
    app: redis-commander
    app.kubernetes.io/instance: redis
  ports:
    - name: http
      port: 8081
      targetPort: http

